language: android

sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-23
    - extra-android-m2repository

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean check

cache:
  directories:
    - $HOME/.gradle

